
title: "Data exploration"
author: "Arfa Aijazi"
date: "2024-05-11"
output: html_document
---
Load libraries
```{r}
library(tidyverse)
library(zoo)
```
Custom plot theme
```{r message=FALSE, warning=FALSE, include=FALSE}
theme_custom <- function() {
  theme_minimal() %+replace%
    theme(legend.position = "top") +
    theme(panel.grid = element_blank()) +
    theme(strip.background = element_blank()) +
    theme(panel.border = element_blank()) +
    theme(panel.background = element_blank()) +
    theme(legend.title = element_blank()) +
    theme(axis.title = element_blank()) +
    theme(text = element_text(size = 7, colour = "#000000")) +
    theme(plot.margin = unit(c(0,0,0,0), 'lines'))
}
```

How many households experience overheating? Pull out the data for the home with the most overheating
```{r}

june <- read_csv("../data/ecobee/Ecobee_2017_1000SFH/Month/Jun.csv", locale = locale(encoding="latin1"))

june <- june %>%
  rename(home.id = names(.)[1])

overheating_homes <- june %>%
  arrange(DateTime) %>%
  group_by(home.id) %>%
  mutate(rolling.mean.thermostat_8hr = rollmean(Thermostat_Temperature, k = 96, fill = NA)) %>%
  mutate(rolling.mean.outdoor_8hr = rollmean(T_out, k = 96, fill = NA)) %>%
  mutate(temp_cond = ifelse(rolling.mean.thermostat_8hr > 82.4, "Too hot",
                            ifelse(rolling.mean.thermostat_8hr < 64.4, "Too cold", "Safe temp"))) %>%
  drop_na(temp_cond) %>%
  mutate(temp_cond = factor(temp_cond, levels = c("Too hot", "Safe temp", "Too cold"))) %>%
  mutate(exceedance_hot = rolling.mean.thermostat_8hr - 82.4) %>%
  mutate(exceedance_overheat = ifelse(exceedance_hot > 0, exceedance_hot, 0)) %>%
  mutate(exceedance_cold = rolling.mean.thermostat_8hr - 64.4) %>%
  mutate(exceedance_undercool = ifelse(exceedance_cold < 0, exceedance_cold, 0))

exceedance_homes <- overheating_homes %>%
  group_by(home.id) %>%
  summarise(total_exceedance_overheat = sum(exceedance_overheat), 
            total_exceedance_undercool = sum(exceedance_undercool)) %>%
  filter(total_exceedance_overheat > 0 | total_exceedance_undercool < 0) %>%
  pivot_longer(cols = starts_with("total_exceedance"), names_to = "Type", values_to = "Exceedance_15")

n = 9

exceedance_homes <- exceedance_homes %>%
  arrange(desc(Exceedance_15))
hottest_home.id_n <- exceedance_homes$home.id[1:n]

exceedance_homes <- exceedance_homes %>%
  arrange(Exceedance_15)
coldest_home.id_n <- exceedance_homes$home.id[1:n]

hottest_n_homes <- overheating_homes %>%
  filter(home.id %in% hottest_home.id_n)

hottest_home <- overheating_homes %>%
  filter(home.id == hottest_home.id_n[1])

coldest_n_homes <- overheating_homes %>%
  filter(home.id %in% coldest_home.id_n)
```

```{r}
ggplot(data = hottest_home, aes(x = DateTime, y = rolling.mean.thermostat_8hr, colour = temp_cond)) +
  geom_line(aes(y = rolling.mean.outdoor_8hr), colour = "#bbbbbb") +
  geom_hline(yintercept = 82.4) +
  geom_point() +
  theme_custom()
```
```{r}
ggplot(data = hottest_home, aes(x = DateTime, y = rolling.mean.thermostat_8hr, colour = HvacMode)) +
  geom_line(aes(y = rolling.mean.outdoor_8hr), colour = "#bbbbbb") +
  geom_hline(yintercept = 82.4) +
  geom_point() +
  theme_custom()
```
```{r}
ggplot(data = hottest_n_homes, aes(x = DateTime, y = rolling.mean.thermostat_8hr, colour = temp_cond)) +
  geom_line(aes(y = rolling.mean.outdoor_8hr), colour = "#bbbbbb") +
  geom_hline(yintercept = 82.4) +
  geom_point() +
  facet_wrap(vars(home.id)) +
  theme_custom()
```

```{r}
ggplot(data = hottest_n_homes, aes(x = DateTime, y = rolling.mean.thermostat_8hr, colour = HvacMode)) +
  geom_line(aes(y = rolling.mean.outdoor_8hr), colour = "#bbbbbb") +
  geom_hline(yintercept = 82.4) +
  geom_point() +
  facet_wrap(vars(home.id)) +
  theme_custom()
```
